package web

// shellScript is the frame's behaviour, shared by every workspace page: its
// menus, dialogs, the Ctrl/Cmd+K switcher, the member's preferences, the Home
// sidebar's per-section order and filters, the narrow navigation drawer, and
// the global keyboard layer declared in keyboard.go. It carries no template
// action, so its hash is exact (see workspaceContentSecurityPolicy).
//
// Everything a page needs to work without it is ordinary markup: every menu is
// a <details> disclosure, every dialog opener is a link to a page that renders
// the same form, and every action is a form.
const shellScript = `<script>(function(){
var root=document.documentElement;
var apple=/Mac|iPhone|iPad/.test(navigator.platform||'');
function primary(event){return apple?event.metaKey&&!event.ctrlKey:event.ctrlKey&&!event.metaKey}
function ownPath(value){return typeof value==='string'&&value.charAt(0)==='/'&&value.charAt(1)!=='/'}
function visible(node){return !!(node&&(node.offsetParent||node.getClientRects().length))}
function all(selector,scope){return Array.prototype.slice.call((scope||document).querySelectorAll(selector))}
var statusRegion=document.getElementById('shell-status');
function say(text){if(!statusRegion)return;statusRegion.textContent='';window.setTimeout(function(){statusRegion.textContent=text},40)}
function go(href){if(ownPath(href)){window.location.assign(href);return true}return false}
var shell=document.querySelector('.shell');
var channel=shell?shell.getAttribute('data-channel')||'':'';
function withChannel(path){if(!channel)return path;return path+(path.indexOf('?')<0?'?':'&')+'channel='+encodeURIComponent(channel)}

var prefix='sameoldchat-pref:';
function storageKey(key){return key==='theme'?'sameoldchat-theme':prefix+key}
function readPref(key,fallback){try{var value=window.localStorage.getItem(storageKey(key));return value===null?fallback:value}catch(error){return fallback}}
function writePref(key,value){try{window.localStorage.setItem(storageKey(key),value)}catch(error){}try{document.dispatchEvent(new CustomEvent('sameoldchat:preference',{detail:{key:key,value:value}}))}catch(error){}}
window.sameoldchatPreferences={get:readPref,set:writePref};
var darkQuery=window.matchMedia?window.matchMedia('(prefers-color-scheme: dark)'):null;
function applyTheme(){var theme=readPref('theme','system');var dark=theme==='dark'||(theme!=='light'&&!!(darkQuery&&darkQuery.matches));root.setAttribute('data-theme',dark?'dark':'light');root.setAttribute('data-theme-explicit','')}
if(darkQuery){if(typeof darkQuery.addEventListener==='function')darkQuery.addEventListener('change',applyTheme);else if(typeof darkQuery.addListener==='function')darkQuery.addListener(applyTheme)}
function loadPreferenceInputs(scope){all('[data-preference]',scope).forEach(function(input){var key=input.getAttribute('data-preference');var fallback=input.getAttribute('data-default');var value=readPref(key,null);if(input.type==='checkbox'){input.checked=value===null?fallback==='true':value==='true'}else if(input.type==='radio'){var current=value===null?null:value;if(current===null){var group=all('[data-preference="'+key+'"]',scope);var defaulted=group.filter(function(item){return item.hasAttribute('data-default')})[0];current=defaulted?defaulted.value:''}input.checked=input.value===current}else{input.value=value===null?(fallback||''):value}})}
document.addEventListener('change',function(event){var input=event.target;if(!input||!input.hasAttribute||!input.hasAttribute('data-preference'))return;var key=input.getAttribute('data-preference');writePref(key,input.type==='checkbox'?(input.checked?'true':'false'):input.value);if(key==='theme')applyTheme();applySidebar();say('Preference saved.')});
loadPreferenceInputs(document);

function openMenus(){return all('details[data-menu][open]')}
function menuList(details){for(var index=0;index<details.children.length;index++){if(details.children[index].classList.contains('menu-list'))return details.children[index]}return null}
function menuItems(list){return all('[role=menuitem],[role=menuitemradio],[role=menuitemcheckbox]',list).filter(function(item){var owner=item.closest('.menu-list');return owner===list||(item.tagName==='SUMMARY'&&item.parentElement.parentElement===list)||(item.tagName==='SUMMARY'&&item.parentElement.closest('.menu-list')===list)}).filter(visible)}
function closeMenu(details,focusSummary){if(!details.open)return;details.open=false;if(focusSummary){var summary=details.querySelector('summary');if(summary)summary.focus()}}
function closeMenus(except){openMenus().forEach(function(details){if(except&&(details===except||details.contains(except)))return;details.open=false})}
var keyboardOpen=false;
document.addEventListener('toggle',function(event){var details=event.target;if(!details||!details.matches||!details.matches('details[data-menu]'))return;var summary=details.querySelector('summary');if(summary)summary.setAttribute('aria-expanded',details.open?'true':'false');if(!details.open)return;closeMenus(details);var list=menuList(details);if(list&&keyboardOpen){var items=menuItems(list);if(items.length)items[0].focus()}keyboardOpen=false},true);
document.addEventListener('keydown',function(event){var summary=event.target&&event.target.closest?event.target.closest('details[data-menu]>summary'):null;if(summary&&(event.key==='Enter'||event.key===' '||event.key==='ArrowDown')){var details=summary.parentElement;keyboardOpen=true;if(event.key==='ArrowDown'||(event.key==='ArrowRight'&&details.classList.contains('submenu'))){event.preventDefault();if(!details.open)details.open=true;else{var list=menuList(details);var items=list?menuItems(list):[];if(items.length)items[0].focus()}}return}
if(summary&&event.key==='ArrowRight'&&summary.parentElement.classList.contains('submenu')){event.preventDefault();keyboardOpen=true;summary.parentElement.open=true;return}
var list=event.target&&event.target.closest?event.target.closest('details[data-menu][open]>.menu-list'):null;if(!list)return;var owner=list.parentElement;var items=menuItems(list);var index=items.indexOf(document.activeElement);
if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(!items.length)return;var next=event.key==='ArrowDown'?(index+1)%items.length:(index<=0?items.length-1:index-1);items[next].focus();return}
if(event.key==='Home'||event.key==='End'){event.preventDefault();if(items.length)items[event.key==='Home'?0:items.length-1].focus();return}
if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeMenu(owner,true);return}
if(event.key==='ArrowLeft'&&owner.classList.contains('submenu')){event.preventDefault();closeMenu(owner,true);return}
if(event.key==='Tab'){closeMenus()}},true);
document.addEventListener('pointerdown',function(event){var inside=event.target&&event.target.closest?event.target.closest('details[data-menu]'):null;closeMenus(inside)});
document.addEventListener('click',function(event){var item=event.target&&event.target.closest?event.target.closest('.menu-list [role=menuitem],.menu-list [role=menuitemradio]'):null;if(!item||item.tagName==='SUMMARY')return;window.setTimeout(function(){closeMenus()},0)});

function focusTarget(trigger){if(!trigger||!document.contains(trigger))return null;if(visible(trigger))return trigger;var details=trigger.closest('details[data-menu]');while(details&&details.parentElement&&details.parentElement.closest('details[data-menu]'))details=details.parentElement.closest('details[data-menu]');var summary=details?details.querySelector('summary'):null;return summary&&visible(summary)?summary:null}
function openDialog(dialog,trigger){if(!dialog||typeof dialog.showModal!=='function')return false;closeMenus();if(dialog.open&&!dialog.matches(':modal')){dialog.sameoldchatReopening=true;dialog.close()}if(!dialog.open)dialog.showModal();dialog.sameoldchatTrigger=trigger||document.activeElement;var initial=dialog.querySelector('[data-initial-focus]')||dialog.querySelector('h2[tabindex]');if(initial)initial.focus();try{dialog.dispatchEvent(new CustomEvent('sameoldchat:open'))}catch(error){}return true}
var dialogInitializers=[];
function dialogByID(id){var dialog=document.getElementById(id);if(dialog)return dialog;var source=document.querySelector('template[data-dialog-template="'+id+'"]');if(!source||!source.content||!source.content.firstElementChild)return null;dialog=document.importNode(source.content.firstElementChild,true);document.body.appendChild(dialog);dialogInitializers.forEach(function(initialize){initialize(dialog)});return dialog}
window.sameoldchatOpenDialog=function(id,trigger){return openDialog(dialogByID(id),trigger)};
document.addEventListener('close',function(event){var dialog=event.target;if(!dialog||dialog.tagName!=='DIALOG')return;if(dialog.sameoldchatReopening){dialog.sameoldchatReopening=false;event.stopImmediatePropagation();return}var target=focusTarget(dialog.sameoldchatTrigger);dialog.sameoldchatTrigger=null;if(target)window.setTimeout(function(){target.focus()},0)},true);
document.addEventListener('click',function(event){var opener=event.target&&event.target.closest?event.target.closest('[data-dialog-open]'):null;if(opener){var dialog=dialogByID(opener.getAttribute('data-dialog-open'));if(dialog&&openDialog(dialog,opener)){event.preventDefault();return}}var closer=event.target&&event.target.closest?event.target.closest('[data-dialog-close]'):null;if(closer){var owner=closer.closest('dialog');if(owner){event.preventDefault();owner.close()}}});
all('dialog[data-autoopen]').forEach(function(dialog){openDialog(dialog,document.querySelector(dialog.getAttribute('data-trigger')||'#conversation-name-button'))});

function selectTab(tab,focus){var list=tab.closest('[role=tablist]');all('[role=tab]',list).forEach(function(other){var selected=other===tab;other.setAttribute('aria-selected',selected?'true':'false');other.tabIndex=selected?0:-1;var panel=document.getElementById(other.getAttribute('aria-controls'));if(panel)panel.hidden=!selected});if(focus)tab.focus()}
document.addEventListener('click',function(event){var tab=event.target&&event.target.closest?event.target.closest('[data-shell-tabs] [role=tab]'):null;if(tab&&(tab.tagName==='BUTTON'||tab.tagName==='A')){if(event.ctrlKey||event.metaKey||event.shiftKey)return;event.preventDefault();selectTab(tab,false)}});
document.addEventListener('keydown',function(event){var tab=event.target&&event.target.closest?event.target.closest('[data-shell-tabs] [role=tab]'):null;if(!tab||(tab.tagName!=='BUTTON'&&tab.tagName!=='A'))return;var list=tab.closest('[role=tablist]');var tabs=all('[role=tab]',list);var index=tabs.indexOf(tab);var vertical=list.getAttribute('aria-orientation')==='vertical';var next=-1;if(event.key===(vertical?'ArrowDown':'ArrowRight'))next=(index+1)%tabs.length;if(event.key===(vertical?'ArrowUp':'ArrowLeft'))next=(index-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next<0)return;event.preventDefault();selectTab(tabs[next],true)});

var switcher=null,switcherQuery=null,switcherList=null,switcherEmpty=null,switcherGroup=null;
function recentConversations(){try{var value=JSON.parse(readPref('recent-conversations','[]'));return Array.isArray(value)?value:[]}catch(error){return[]}}
function rememberConversation(id){if(!id)return;var list=recentConversations().filter(function(item){return item!==id});list.unshift(id);writePref('recent-conversations',JSON.stringify(list.slice(0,12)))}
function switcherOptions(){return switcherList?all('[role=option]',switcherList):[]}
function shownOptions(){return switcherOptions().filter(function(option){return !option.hidden})}
function setActiveOption(option){switcherOptions().forEach(function(item){item.setAttribute('aria-selected',item===option?'true':'false')});if(!switcherQuery)return;if(option){switcherQuery.setAttribute('aria-activedescendant',option.id);option.scrollIntoView({block:'nearest'})}else{switcherQuery.removeAttribute('aria-activedescendant')}}
function rank(name,query){name=name.toLowerCase();if(name===query)return 0;if(name.indexOf(query)===0)return 1;if(name.split(/[\s,._-]+/).some(function(word){return word.indexOf(query)===0}))return 2;if(name.indexOf(query)>=0)return 3;return -1}
function renderSwitcher(){if(!switcherList||!switcherQuery)return;var query=switcherQuery.value.trim().toLowerCase();var options=switcherOptions();var chosen=[];
if(!query){var recent=recentConversations();recent.forEach(function(id){var match=options.filter(function(option){return option.getAttribute('data-conversation-id')===id&&id!==channel})[0];if(match&&chosen.length<10)chosen.push(match)});if(!chosen.length)chosen=options.filter(function(option){return option.getAttribute('data-kind')!=='app'}).slice(0,10);if(switcherGroup)switcherGroup.textContent=recent.length?'Recent':'Conversations'}
else{chosen=options.map(function(option){return{option:option,score:rank(option.getAttribute('data-conversation-name')||'',query)}}).filter(function(entry){return entry.score>=0}).sort(function(left,right){return left.score-right.score||(left.option.getAttribute('data-conversation-name')||'').localeCompare(right.option.getAttribute('data-conversation-name')||'')}).slice(0,50).map(function(entry){return entry.option});if(switcherGroup)switcherGroup.textContent='Results'}
options.forEach(function(option){option.hidden=chosen.indexOf(option)<0});chosen.forEach(function(option){switcherList.appendChild(option)});
if(switcherEmpty)switcherEmpty.textContent=chosen.length?'':(query?'No results for “'+switcherQuery.value.trim()+'”':'No results');if(switcherGroup)switcherGroup.hidden=!chosen.length;switcherQuery.setAttribute('aria-expanded',chosen.length?'true':'false');setActiveOption(chosen[0]||null)}
function bindSwitcher(){if(switcher)return true;switcher=dialogByID('conversation-switcher');if(!switcher)return false;switcherQuery=document.getElementById('conversation-switcher-query');switcherList=document.getElementById('conversation-switcher-results');switcherEmpty=document.getElementById('conversation-switcher-empty');switcherGroup=document.getElementById('conversation-switcher-group');
if(switcherQuery){switcherQuery.addEventListener('input',renderSwitcher);switcherQuery.addEventListener('keydown',switcherKeydown)}
if(switcherList){switcherList.addEventListener('mousemove',function(event){var option=event.target.closest('[role=option]');if(option&&option.getAttribute('aria-selected')!=='true')setActiveOption(option)});switcherList.addEventListener('click',function(event){var option=event.target.closest('[role=option]');if(!option)return;rememberConversation(option.getAttribute('data-conversation-id'));go(option.getAttribute('data-href'))})}
return true}
function openSwitcher(trigger){if(!bindSwitcher())return false;if(switcherQuery)switcherQuery.value='';renderSwitcher();openDialog(switcher,trigger);if(switcherQuery)switcherQuery.focus();return true}
window.sameoldchatOpenSwitcher=openSwitcher;
function switcherKeydown(event){var shown=shownOptions();var active=shown.filter(function(option){return option.getAttribute('aria-selected')==='true'})[0];var index=shown.indexOf(active);if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(!shown.length)return;setActiveOption(shown[event.key==='ArrowDown'?(index+1)%shown.length:(index<=0?shown.length-1:index-1)]);return}if(event.key==='Enter'){event.preventDefault();if(active){rememberConversation(active.getAttribute('data-conversation-id'));go(active.getAttribute('data-href'))}else say('No results.')}}
rememberConversation(shell&&shell.getAttribute('data-conversation-open')==='true'?channel:'');

var keyboardHelp=null,keyboardHelpQuery=null,keyboardHelpEmpty=null;
function filterKeyboardHelp(){if(!keyboardHelp)return;var term=keyboardHelpQuery?keyboardHelpQuery.value.trim().toLowerCase():'';var shown=0;all('[data-keyboard-row]',keyboardHelp).forEach(function(row){var match=!term||(row.getAttribute('data-keyboard-search')||'').indexOf(term)>=0;row.hidden=!match;if(match)shown++});all('[data-keyboard-section]',keyboardHelp).forEach(function(section){section.hidden=!section.querySelector('[data-keyboard-row]:not([hidden])')});if(keyboardHelpEmpty)keyboardHelpEmpty.hidden=shown>0}
function showPlatformChords(root){all('[data-keyboard-apple]',root).forEach(function(node){node.hidden=!apple});all('[data-keyboard-other]',root).forEach(function(node){node.hidden=apple})}
showPlatformChords(document);dialogInitializers.push(showPlatformChords);
function syncComposerPreferences(){var enter='send',markup=false;try{enter=window.localStorage.getItem('sameoldchat-composer-enter')==='newline'?'newline':'send';markup=window.localStorage.getItem('sameoldchat-composer-markup')==='true'}catch(error){}all('[data-composer-preference]').forEach(function(input){var key=input.getAttribute('data-composer-preference');if(key==='enter')input.checked=input.value===enter;if(key==='markup')input.checked=markup})}
syncComposerPreferences();dialogInitializers.push(function(){syncComposerPreferences()});dialogInitializers.push(loadPreferenceInputs);
document.addEventListener('change',function(event){var input=event.target;var key=input&&input.getAttribute?input.getAttribute('data-composer-preference'):null;if(!key||window.sameoldchatComposer)return;try{if(key==='enter'&&input.checked)window.localStorage.setItem('sameoldchat-composer-enter',input.value==='newline'?'newline':'send');if(key==='markup')window.localStorage.setItem('sameoldchat-composer-markup',input.checked?'true':'false')}catch(error){}say(key==='enter'?(input.value==='newline'?'Enter now starts a new line.':'Enter now sends a message.'):'Preference saved.')});
function bindKeyboardHelp(){if(keyboardHelp)return true;keyboardHelp=dialogByID('keyboard-help');if(!keyboardHelp)return false;keyboardHelpQuery=document.getElementById('keyboard-help-query');keyboardHelpEmpty=document.getElementById('keyboard-help-empty');keyboardHelp.addEventListener('sameoldchat:open',function(){if(keyboardHelpQuery){keyboardHelpQuery.value='';filterKeyboardHelp();keyboardHelpQuery.focus()}});if(keyboardHelpQuery)keyboardHelpQuery.addEventListener('input',filterKeyboardHelp);return true}
dialogInitializers.push(function(dialog){if(dialog.id==='keyboard-help')bindKeyboardHelp()});
function openKeyboardHelp(){return bindKeyboardHelp()&&openDialog(keyboardHelp,document.activeElement)}

var timezone='UTC';try{timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}catch(error){}
function localize(root){all('[data-browser-timezone]',root).forEach(function(input){input.value=timezone});
all('time[data-local-time]',root).forEach(function(node){var value=new Date(node.getAttribute('datetime'));if(!isNaN(value.getTime()))node.textContent=value.toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'})});}
localize(document);dialogInitializers.push(localize);
all('[data-until-tomorrow]').forEach(function(button){var now=new Date();var tomorrow=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,9,0,0);button.value=String(Math.max(1,Math.min(1440,Math.round((tomorrow-now)/60000))))});

function initStatusForms(root){all('[data-status-form]',root).forEach(function(form){var emoji=form.querySelector('[name=status_emoji]');var text=form.querySelector('[name=status_text]');var clear=form.querySelector('[name=clear_after]');var custom=form.querySelector('[data-status-custom]');function sync(){if(custom)custom.hidden=!clear||clear.value!=='custom'}sync();if(clear)clear.addEventListener('change',sync);form.addEventListener('click',function(event){var preset=event.target.closest('[data-status-preset]');if(!preset)return;if(emoji)emoji.value=preset.getAttribute('data-emoji')||'';if(text){text.value=preset.getAttribute('data-text')||'';text.focus()}if(clear){clear.value=preset.getAttribute('data-clear')||'never';sync()}})});}
initStatusForms(document);dialogInitializers.push(initStatusForms);

function initSteppedForms(root){all('form[data-stepped]',root).forEach(function(form){var steps=all('[data-step]',form);var step=0;var back=form.querySelector('[data-step-back]');var next=form.querySelector('[data-step-next]');var skip=form.querySelector('[data-step-skip]');var submit=form.querySelector('[data-step-submit]');var name=form.querySelector('[name=name]');var count=form.querySelector('.char-count');var chosen=form.querySelector('[data-people-chosen]');
function show(index){step=index;steps.forEach(function(section,position){section.hidden=position!==index});if(back)back.hidden=index===0;if(next)next.hidden=index===steps.length-1;if(skip)skip.hidden=index!==steps.length-1;if(submit){submit.hidden=index!==steps.length-1;submit.textContent=chosen&&chosen.children.length?'Add':'Create'}var focus=steps[index].querySelector('input:not([type=hidden])');if(focus)focus.focus()}
function update(){if(!name)return;var value=name.value.toLowerCase().replace(/\s+/g,'-');if(value!==name.value){var cursor=name.selectionStart;name.value=value;try{name.setSelectionRange(cursor,cursor)}catch(error){}}if(count)count.textContent=String(80-value.length);if(next&&step===0)next.disabled=!value.trim()}
if(name){name.addEventListener('input',update);update()}
if(next)next.addEventListener('click',function(){if(step===0&&name&&!name.reportValidity())return;show(Math.min(step+1,steps.length-1))});
if(back)back.addEventListener('click',function(){show(Math.max(step-1,0))});
if(skip)skip.addEventListener('click',function(){if(chosen)chosen.innerHTML=''});
form.addEventListener('keydown',function(event){if(event.key==='Enter'&&event.target.tagName==='INPUT'&&step<steps.length-1){event.preventDefault();if(next&&!next.disabled)next.click()}});
var error=form.querySelector('[data-step-error]');
form.addEventListener('submit',function(event){if(!window.fetch||!ownPath(form.getAttribute('action')))return;event.preventDefault();var body=new URLSearchParams(new FormData(form));var submitter=event.submitter;if(submitter)submitter.disabled=true;
fetch(form.getAttribute('action'),{method:'POST',credentials:'same-origin',headers:{'HX-Request':'true','content-type':'application/x-www-form-urlencoded'},body:body.toString()}).then(function(response){var redirect=response.headers.get('HX-Redirect');if(response.ok&&redirect&&ownPath(redirect)){window.location.assign(redirect);return}return response.text().then(function(message){if(submitter)submitter.disabled=false;if(error){error.textContent=(message||'').trim()||'The channel was not created. Try again.';error.hidden=false}show(0);if(error)error.focus()})}).catch(function(){if(submitter)submitter.disabled=false;if(error){error.textContent='The channel was not created because the connection failed. Try again.';error.hidden=false}})});
var dialog=form.closest('dialog');if(dialog)dialog.addEventListener('sameoldchat:open',function(){form.reset();if(chosen)chosen.innerHTML='';if(error){error.hidden=true;error.textContent=''}update();show(0)});show(0)});}
initSteppedForms(document);dialogInitializers.push(initSteppedForms);
function initPeoplePickers(root){all('[data-people-picker]',root).forEach(function(input){var list=document.getElementById(input.getAttribute('aria-controls'));var form=input.form;var chosen=form?form.querySelector('[data-people-chosen]'):null;var timer=0;var request=null;
function choose(option){if(!chosen)return;var id=option.getAttribute('data-user');if(!id||chosen.querySelector('[data-user="'+id+'"]'))return;var item=document.createElement('li');item.setAttribute('data-user',id);item.appendChild(document.createTextNode(option.textContent));var hidden=document.createElement('input');hidden.type='hidden';hidden.name='user_'+id;hidden.value='1';item.appendChild(hidden);var remove=document.createElement('button');remove.type='button';remove.setAttribute('aria-label','Remove '+option.textContent);remove.textContent='×';remove.addEventListener('click',function(){item.remove();input.focus();sync()});item.appendChild(remove);chosen.appendChild(item);input.value='';list.hidden=true;input.setAttribute('aria-expanded','false');sync();say(option.textContent+' will be added.')}
function sync(){var submit=form?form.querySelector('[data-step-submit]'):null;if(submit)submit.textContent=chosen&&chosen.children.length?'Add':'Create'}
function render(people){list.innerHTML='';people.forEach(function(person,index){var option=document.createElement('li');option.setAttribute('role','option');option.id=input.id+'-option-'+index;option.setAttribute('data-user',person.id);option.setAttribute('aria-selected',index===0?'true':'false');option.textContent=person.name;option.addEventListener('mousedown',function(event){event.preventDefault();choose(option)});list.appendChild(option)});list.hidden=!people.length;input.setAttribute('aria-expanded',people.length?'true':'false');if(people.length)input.setAttribute('aria-activedescendant',list.firstChild.id);else input.removeAttribute('aria-activedescendant')}
input.addEventListener('input',function(){window.clearTimeout(timer);var query=input.value.trim();if(!query){render([]);return}timer=window.setTimeout(function(){if(request&&request.abort)request.abort();request=window.AbortController?new AbortController():null;fetch('/app/search/suggestions?q='+encodeURIComponent(query),{credentials:'same-origin',signal:request?request.signal:undefined}).then(function(response){return response.ok?response.json():{items:[]}}).then(function(payload){var people=(payload.items||[]).filter(function(item){return item.kind==='person'}).map(function(item){var match=/[?&]user=([^&]+)/.exec(item.url||'');return{id:match?decodeURIComponent(match[1]):'',name:item.label}}).filter(function(person){return person.id});render(people)}).catch(function(){})},150)});
input.addEventListener('keydown',function(event){var options=all('[role=option]',list);var index=options.findIndex(function(option){return option.getAttribute('aria-selected')==='true'});if((event.key==='ArrowDown'||event.key==='ArrowUp')&&options.length){event.preventDefault();var next=event.key==='ArrowDown'?(index+1)%options.length:(index<=0?options.length-1:index-1);options.forEach(function(option,position){option.setAttribute('aria-selected',position===next?'true':'false')});input.setAttribute('aria-activedescendant',options[next].id);return}if(event.key==='Enter'&&options.length&&!list.hidden){event.preventDefault();event.stopPropagation();choose(options[Math.max(index,0)])}})});}
initPeoplePickers(document);dialogInitializers.push(initPeoplePickers);

var sidebar=document.getElementById('workspace-sidebar');
function sortRows(section,order){var list=section.querySelector('[data-section-list]');if(!list)return;var rows=all(':scope>.side-row',list);rows.sort(function(left,right){if(order==='recent'){return (parseInt(right.getAttribute('data-recent')||'0',10)-parseInt(left.getAttribute('data-recent')||'0',10))||(left.getAttribute('data-name')||'').localeCompare(right.getAttribute('data-name')||'')}if(order==='priority'){return (parseInt(right.getAttribute('data-priority')||'0',10)-parseInt(left.getAttribute('data-priority')||'0',10))||(parseInt(right.getAttribute('data-recent')||'0',10)-parseInt(left.getAttribute('data-recent')||'0',10))}return (left.getAttribute('data-name')||'').localeCompare(right.getAttribute('data-name')||'')});var anchor=list.querySelector(':scope>.side-add,:scope>.side-empty');rows.forEach(function(row){list.insertBefore(row,anchor)})}
function applySidebar(){if(!sidebar)return;all('[data-pref-row]',sidebar).forEach(function(row){var key=row.getAttribute('data-pref-row');row.hidden=readPref(key,row.getAttribute('data-default')||'false')!=='true'});var defaultSort=readPref('sidebar-sort','alpha');var defaultShow=readPref('sidebar-show','all');all('[data-section-key]',sidebar).forEach(function(section){var key=section.getAttribute('data-section-key');var order=readPref('section-sort:'+key,defaultSort);var show=readPref('section-show:'+key,defaultShow);sortRows(section,order);section.setAttribute('data-filter',show);all('[data-section-sort]',section).forEach(function(item){item.setAttribute('aria-checked',item.getAttribute('data-section-sort')===order?'true':'false')});all('[data-section-show]',section).forEach(function(item){item.setAttribute('aria-checked',item.getAttribute('data-section-show')===show?'true':'false')});var toggle=section.querySelector('[data-section-toggle]');if(toggle){var collapsed=readPref('section-collapsed:'+key,'false')==='true';toggle.setAttribute('aria-expanded',collapsed?'false':'true');var list=section.querySelector('[data-section-list]');if(list)all(':scope>.side-row',list).forEach(function(row){row.hidden=collapsed&&!row.querySelector('[aria-current=page]')&&!row.hasAttribute('data-unread')});if(list){var extras=all(':scope>.side-add',list);extras.forEach(function(extra){extra.hidden=collapsed})}}});var hidden=readPref('sidebar-hidden','false')==='true';var workspace=document.querySelector('.shell .workspace');if(workspace&&sidebar&&!narrowMatches()){workspace.classList.toggle('without-pane',hidden);sidebar.hidden=hidden}}
function narrowMatches(){return !!(window.matchMedia&&window.matchMedia('(max-width:800px)').matches)}
document.addEventListener('click',function(event){var target=event.target&&event.target.closest?event.target:null;if(!target)return;var toggle=target.closest('[data-section-toggle]');if(toggle){var section=toggle.closest('[data-section-key]');var key=section.getAttribute('data-section-key');var collapsed=toggle.getAttribute('aria-expanded')==='true';writePref('section-collapsed:'+key,collapsed?'true':'false');applySidebar();return}var sort=target.closest('[data-section-sort]');if(sort){var sortSection=sort.closest('[data-section-key]');writePref('section-sort:'+sortSection.getAttribute('data-section-key'),sort.getAttribute('data-section-sort'));applySidebar();say('Sorted '+(sortSection.getAttribute('aria-label')||'section')+'.');return}var show=target.closest('[data-section-show]');if(show){var showSection=show.closest('[data-section-key]');writePref('section-show:'+showSection.getAttribute('data-section-key'),show.getAttribute('data-section-show'));applySidebar();return}var copy=target.closest('[data-copy-text]');if(copy){event.preventDefault();var value=copy.getAttribute('data-copy-text')||'';if(copy.hasAttribute('data-copy-url'))value=new URL(value,window.location.origin).toString();var done=function(){say(copy.getAttribute('data-copied')||'Copied.')};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(value).then(done,function(){say('Copying is not available in this browser.')});else say('Copying is not available in this browser.')}});
if(sidebar){sidebar.addEventListener('contextmenu',function(event){var row=event.target.closest('.side-row');var menu=row?row.querySelector('details[data-menu]'):null;if(!menu)return;event.preventDefault();keyboardOpen=true;menu.open=true})}
var dragged=null;
if(sidebar){sidebar.addEventListener('dragstart',function(event){var row=event.target.closest&&event.target.closest('.side-row[data-conversation]');if(!row)return;dragged=row;row.setAttribute('data-dragging','');try{event.dataTransfer.setData('text/plain',row.getAttribute('data-name')||'');event.dataTransfer.effectAllowed='move'}catch(error){}});sidebar.addEventListener('dragend',function(){if(dragged)dragged.removeAttribute('data-dragging');dragged=null;all('.drop-target',sidebar).forEach(function(node){node.classList.remove('drop-target')})});sidebar.addEventListener('dragover',function(event){var section=event.target.closest&&event.target.closest('[data-drop-section]');if(!dragged||!section)return;event.preventDefault();all('.drop-target',sidebar).forEach(function(node){if(node!==section)node.classList.remove('drop-target')});section.classList.add('drop-target')});sidebar.addEventListener('drop',function(event){var section=event.target.closest&&event.target.closest('[data-drop-section]');var form=document.getElementById('sidebar-move-form');if(!dragged||!section||!form)return;event.preventDefault();var target=section.getAttribute('data-drop-section');if(target===(dragged.getAttribute('data-section')||''))return;form.querySelector('[name=conversation]').value=dragged.getAttribute('data-conversation');form.querySelector('[name=section]').value=target==='channels'?'':target;form.submit()})}

var navToggle=document.getElementById('nav-toggle');
var navScrim=document.getElementById('nav-scrim');
function setNav(open,focus){if(!sidebar||!navToggle)return;var mobile=narrowMatches();open=mobile&&open;sidebar.classList.toggle('is-open',open);if(navScrim)navScrim.classList.toggle('is-open',open);navToggle.setAttribute('aria-expanded',open?'true':'false');navToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(mobile&&!open)sidebar.setAttribute('inert','');else sidebar.removeAttribute('inert');if(open&&focus){var current=sidebar.querySelector('[aria-current="page"]')||sidebar.querySelector('.side-link,summary');if(current)current.focus()}}
function navFocusables(){return sidebar?all('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex]:not([tabindex="-1"])',sidebar).filter(visible):[]}
function toggleSidebar(){if(!sidebar)return false;if(narrowMatches()){setNav(!sidebar.classList.contains('is-open'),true);return true}writePref('sidebar-hidden',readPref('sidebar-hidden','false')==='true'?'false':'true');applySidebar();say(sidebar.hidden?'Sidebar hidden.':'Sidebar shown.');return true}
if(navToggle){if(!sidebar)navToggle.hidden=true;navToggle.addEventListener('click',function(){setNav(!sidebar.classList.contains('is-open'),true)})}
if(navScrim)navScrim.addEventListener('click',function(){setNav(false,false);if(navToggle)navToggle.focus()});
if(window.matchMedia){var narrowQuery=window.matchMedia('(max-width:800px)');var onNarrow=function(){setNav(false,false);applySidebar()};if(typeof narrowQuery.addEventListener==='function')narrowQuery.addEventListener('change',onNarrow);setNav(false,false)}
applySidebar();

function regions(){return all('.rail,#workspace-sidebar,#workspace-search,.channel-header,#timeline,.shell-main,#thread-messages,#thread-composer,#composer').filter(function(node){return visible(node)||node===document.activeElement})}
function moveRegion(backwards){var list=regions();if(list.length<2)return false;var active=document.activeElement;var current=-1;list.forEach(function(node,index){if(current<0&&(node===active||node.contains(active)))current=index});if(current<0)current=backwards?0:list.length-1;var target=list[backwards?(current+list.length-1)%list.length:(current+1)%list.length];var focusable=target.matches('input,textarea,select,button,a[href]')?target:target.querySelector('[aria-current=page],[contenteditable="true"]:not([hidden]),input:not([type=hidden]):not([hidden]),textarea:not([hidden]),select,button,a[href],summary,[tabindex="-1"]');var destination=focusable||target;if(!destination.hasAttribute('tabindex')&&!destination.matches('input,textarea,select,button,a[href],summary'))destination.setAttribute('tabindex','-1');destination.focus();say('Moved to '+(target.getAttribute('aria-label')||target.id.replace(/[-_]/g,' ')||'section'));return true}
function sidebarLinks(){return sidebar?all('.side-section .side-link',sidebar).filter(function(link){return visible(link)||link.getAttribute('aria-current')==='page'}):[]}

document.addEventListener('keydown',function(event){if(event.defaultPrevented)return;var key=typeof event.key==='string'?event.key.toLowerCase():'';
if(event.key==='Tab'&&sidebar&&sidebar.classList.contains('is-open')){var focusable=navFocusables();if(focusable.length){var first=focusable[0];var last=focusable[focusable.length-1];var active=document.activeElement;if(event.shiftKey&&(active===first||!sidebar.contains(active))){event.preventDefault();last.focus();return}if(!event.shiftKey&&(active===last||!sidebar.contains(active))){event.preventDefault();first.focus();return}}}
if(event.key==='Escape'&&sidebar&&sidebar.classList.contains('is-open')&&!document.querySelector('dialog[open]')){event.preventDefault();event.stopImmediatePropagation();setNav(false,false);if(navToggle)navToggle.focus();return}
if(event.ctrlKey&&!event.metaKey&&!event.altKey&&(key==='3'||event.code==='Digit3')&&(apple?!event.shiftKey:event.shiftKey)){var activity=document.getElementById('activity-link');if(activity&&go(activity.getAttribute('href'))){event.preventDefault()}return}
if(primary(event)&&!event.altKey&&!event.shiftKey){
if(key==='k'){if(openSwitcher(document.activeElement))event.preventDefault();return}
if(key==='g'){var search=document.getElementById('workspace-search');if(search){event.preventDefault();search.focus();search.select()}return}
if(key==='/'){if(openKeyboardHelp())event.preventDefault();return}
if(key===','){var preferences=dialogByID('preferences');if(openDialog(preferences,document.activeElement))event.preventDefault();return}
if(key==='n'){event.preventDefault();go(withChannel('/app/dms')+'#new-dm');return}
if(key==='.'){if(toggleRightPane())event.preventDefault();return}}
if(primary(event)&&!event.altKey&&event.shiftKey){
var destinations={k:'/app/dms',a:'/app/unreads',t:'/app/threads',s:'/app/later',l:'/app/channels',e:'/app/members'};
if(destinations[key]){event.preventDefault();go(withChannel(destinations[key]));return}
if(key==='y'){var status=dialogByID('status-dialog');if(openDialog(status,document.activeElement))event.preventDefault();return}
if(key==='d'){if(toggleSidebar())event.preventDefault();return}}
if(primary(event)&&!event.altKey&&event.key==='F6'){if(moveRegion(event.shiftKey))event.preventDefault();return}
if(event.altKey&&!event.ctrlKey&&!event.metaKey&&(event.key==='ArrowUp'||event.key==='ArrowDown')){var links=sidebarLinks();if(event.shiftKey)links=links.filter(function(link){return link.classList.contains('is-unread')||link.getAttribute('aria-current')==='page'});var others=links.filter(function(link){return link.getAttribute('aria-current')!=='page'});if(event.shiftKey&&!others.length){event.preventDefault();say('No unread conversations.');return}if(links.length<2)return;var here=links.findIndex(function(link){return link.getAttribute('aria-current')==='page'});var step=event.key==='ArrowDown'?1:-1;var next=here<0?(step>0?0:links.length-1):(here+step+links.length)%links.length;if(go(links[next].getAttribute('href')))event.preventDefault()}});
function toggleRightPane(){var closer=document.querySelector('[data-thread-close]');if(closer){closer.click();return true}var details=document.getElementById('conversation-details');if(details&&details.open){details.close();return true}var trigger=document.getElementById('conversation-name-button');if(trigger){trigger.click();return true}return false}

function adoptDetails(dialog,trigger){var existing=document.getElementById('conversation-details');if(existing&&existing!==dialog)existing.remove();document.body.appendChild(dialog);loadPreferenceInputs(dialog);var tab=dialog.getAttribute('data-initial-tab');if(tab){var initial=dialog.querySelector('[role=tab][data-tab="'+tab+'"]');if(initial)selectTab(initial,false)}openDialog(dialog,trigger)}
document.addEventListener('click',function(event){var trigger=event.target&&event.target.closest?event.target.closest('[data-details-trigger]'):null;if(!trigger||event.ctrlKey||event.metaKey||event.shiftKey)return;var href=trigger.getAttribute('href')||trigger.getAttribute('data-details-href');if(!ownPath(href)||!window.fetch||!window.DOMParser)return;event.preventDefault();closeMenus();fetch(href,{credentials:'same-origin'}).then(function(response){if(!response.ok)throw new Error('details');return response.text()}).then(function(html){var fresh=new DOMParser().parseFromString(html,'text/html').getElementById('conversation-details');if(!fresh)throw new Error('details');fresh.removeAttribute('open');fresh.removeAttribute('data-autoopen');adoptDetails(document.importNode(fresh,true),document.getElementById('conversation-name-button')||trigger)}).catch(function(){window.location.assign(href)})});
document.addEventListener('close',function(event){var dialog=event.target;if(!dialog||dialog.id!=='conversation-details')return;var closeURL=dialog.getAttribute('data-close-url');if(closeURL&&/[?&]details=1/.test(window.location.search)&&window.history&&typeof window.history.replaceState==='function'){try{window.history.replaceState(null,'',closeURL)}catch(error){}}},true);
document.addEventListener('input',function(event){var search=event.target;if(!search||!search.hasAttribute||!search.hasAttribute('data-member-filter'))return;var term=search.value.trim().toLowerCase();var list=document.getElementById(search.getAttribute('aria-controls'));if(!list)return;var shown=0;all('[data-member-name]',list).forEach(function(item){var match=!term||(item.getAttribute('data-member-name')||'').toLowerCase().indexOf(term)>=0;item.hidden=!match;if(match)shown++});var empty=document.getElementById(search.getAttribute('data-empty'));if(empty)empty.textContent=shown?'':'No members match “'+search.value.trim()+'”.'});
})();</script>`
