package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type manifest struct {
	Modules []module `json:"modules"`
	Targets []target `json:"targets"`
}

type module struct {
	Name                 string   `json:"name"`
	APIImport            string   `json:"api_import"`
	ImplementationImport string   `json:"implementation_import"`
	TransportImport      string   `json:"transport_import"`
	BlobImport           string   `json:"blob_import"`
	ImplementationType   string   `json:"implementation_type"`
	Dependencies         []string `json:"dependencies"`
}

type target struct {
	Name      string              `json:"name"`
	Mode      string              `json:"mode"`
	Storage   string              `json:"storage"`
	Processes map[string][]string `json:"processes"`
	Replicas  map[string]int      `json:"replicas"`
}

func main() {
	manifestPath := flag.String("manifest", "modules.json", "module manifest")
	outPath := flag.String("out", "bindings.go", "generated Go file")
	check := flag.Bool("check", false, "verify the existing output instead of writing it")
	flag.Parse()
	if err := generate(*manifestPath, *outPath, *check); err != nil {
		fmt.Fprintln(os.Stderr, "modulegen:", err)
		os.Exit(1)
	}
}

func generate(manifestPath, outPath string, check bool) error {
	body, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}
	var value manifest
	if err := json.Unmarshal(body, &value); err != nil {
		return err
	}
	if err := validate(value); err != nil {
		return err
	}
	if len(value.Modules) == 0 {
		return errors.New("manifest must declare at least one module")
	}
	imports := []string{"\"github.com/sameoldchat/sameoldchat/internal/auth\"", "\"github.com/sameoldchat/sameoldchat/internal/store\"", "\"google.golang.org/grpc\""}
	for _, item := range value.Modules {
		imports = append(imports, fmt.Sprintf("%q", item.ImplementationImport), fmt.Sprintf("%q", item.APIImport), fmt.Sprintf("%s %q", transportAlias(item.Name), item.TransportImport))
		if item.BlobImport != "" {
			imports = append(imports, fmt.Sprintf("%q", item.BlobImport))
		}
	}
	sort.Strings(imports)
	var output strings.Builder
	output.WriteString("// Code generated by modulegen; DO NOT EDIT.\n\npackage generated\n\nimport (\n")
	for _, item := range imports {
		output.WriteString("\t" + item + "\n")
	}
	output.WriteString(")\n\n")
	output.WriteString("type ProcessProfile struct { Modules []string; Replicas int }\n\n")
	output.WriteString("type TargetProfile struct { Name string; Mode string; Storage string; Processes map[string]ProcessProfile }\n\n")
	output.WriteString("var TargetProfiles = map[string]TargetProfile{\n")
	targets := append([]target(nil), value.Targets...)
	sort.Slice(targets, func(i, j int) bool { return targets[i].Name < targets[j].Name })
	for _, item := range targets {
		output.WriteString(fmt.Sprintf("\t%q: {Name: %q, Mode: %q, Storage: %q, Processes: map[string]ProcessProfile{\n", item.Name, item.Name, item.Mode, item.Storage))
		processes := make([]string, 0, len(item.Processes))
		for process := range item.Processes {
			processes = append(processes, process)
		}
		sort.Strings(processes)
		for _, process := range processes {
			modules := append([]string(nil), item.Processes[process]...)
			replicas := item.Replicas[process]
			output.WriteString(fmt.Sprintf("\t\t%q: {Modules: []string{", process))
			for index, module := range modules {
				if index > 0 {
					output.WriteString(", ")
				}
				output.WriteString(fmt.Sprintf("%q", module))
			}
			output.WriteString(fmt.Sprintf("}, Replicas: %d},\n", replicas))
		}
		output.WriteString("\t}},\n")
	}
	output.WriteString("}\n\n")
	for _, item := range value.Modules {
		name := exported(item.Name)
		transport := transportAlias(item.Name)
		if item.BlobImport != "" {
			output.WriteString(fmt.Sprintf("func Provide%sServiceLocal(dependencies store.Store, blobs blob.Store) %s.Service {\n\treturn %s.%s{Store: dependencies, Blob: blobs}\n}\n\n", name, packageName(item.APIImport), packageName(item.ImplementationImport), item.ImplementationType))
		} else {
			output.WriteString(fmt.Sprintf("func Provide%sServiceLocal(dependencies store.Store) %s.Service {\n\treturn %s.%s{Store: dependencies}\n}\n\n", name, packageName(item.APIImport), packageName(item.ImplementationImport), item.ImplementationType))
		}
		output.WriteString(fmt.Sprintf("func Provide%sServiceRemote(connection grpc.ClientConnInterface) (%s.Service, auth.TokenStore, auth.SessionStore, auth.SessionRevoker, error) {\n\tremote, err := %s.NewRemote(connection)\n\tif err != nil {\n\t\treturn nil, nil, nil, nil, err\n\t}\n\treturn remote, remote, remote, remote, nil\n}\n\n", name, packageName(item.APIImport), transport))
		output.WriteString(fmt.Sprintf("func Register%sServiceServer(registrar grpc.ServiceRegistrar, implementation %s.Service, tokens auth.TokenStore, sessions auth.SessionStore, revoker auth.SessionRevoker) error {\n\treturn %s.RegisterServer(registrar, implementation, tokens, sessions, revoker)\n}\n\n", name, packageName(item.APIImport), transport))
	}
	generated, err := format.Source([]byte(output.String()))
	if err != nil {
		return fmt.Errorf("format generated bindings: %w", err)
	}
	if check {
		actual, err := os.ReadFile(outPath)
		if err != nil {
			return err
		}
		if !bytes.Equal(actual, generated) {
			return errors.New("generated bindings are stale; run go generate ./...")
		}
		return nil
	}
	return os.WriteFile(outPath, generated, 0o644)
}

func validate(value manifest) error {
	known := make(map[string]bool, len(value.Modules))
	for _, item := range value.Modules {
		if item.Name == "" || item.APIImport == "" || item.ImplementationImport == "" || item.TransportImport == "" || item.ImplementationType == "" {
			return errors.New("module name, API import, implementation import, transport import, and implementation type are required")
		}
		if known[item.Name] {
			return fmt.Errorf("duplicate module %q", item.Name)
		}
		known[item.Name] = true
	}
	for _, item := range value.Modules {
		for _, dependency := range item.Dependencies {
			if dependency == "" {
				return fmt.Errorf("module %q has an empty dependency", item.Name)
			}
		}
	}
	targetNames := make(map[string]bool, len(value.Targets))
	for _, item := range value.Targets {
		if item.Name == "" {
			return errors.New("target name is required")
		}
		if targetNames[item.Name] {
			return fmt.Errorf("duplicate target %q", item.Name)
		}
		targetNames[item.Name] = true
		if item.Mode != "monolith" && item.Mode != "separate" {
			return fmt.Errorf("target %q must select monolith or separate mode", item.Name)
		}
		if item.Storage != "memory" && item.Storage != "sqlite" && item.Storage != "dqlite" {
			return fmt.Errorf("target %q must select memory, sqlite, or dqlite storage", item.Name)
		}
		if item.Mode == "monolith" && len(item.Processes) != 1 {
			return fmt.Errorf("monolith target %q must place every module in exactly one process", item.Name)
		}
		for process := range item.Replicas {
			if _, ok := item.Processes[process]; !ok {
				return fmt.Errorf("target %q has a replica count for unknown process %q", item.Name, process)
			}
		}
		seen := make(map[string]bool)
		for process, names := range item.Processes {
			if process == "" {
				return errors.New("target has an empty process name")
			}
			replicas, ok := item.Replicas[process]
			if !ok || replicas < 1 {
				return fmt.Errorf("target %q process %q must have a positive replica count", item.Name, process)
			}
			if item.Storage == "memory" && replicas > 1 {
				return fmt.Errorf("target %q cannot use memory storage with multiple replicas", item.Name)
			}
			for _, name := range names {
				if !known[name] {
					return fmt.Errorf("target %q references unknown module %q", item.Name, name)
				}
				if seen[name] {
					return fmt.Errorf("target %q places module %q more than once", item.Name, name)
				}
				seen[name] = true
			}
		}
		if len(seen) != len(value.Modules) {
			return fmt.Errorf("target %q does not place every module exactly once", item.Name)
		}
		if item.Mode == "monolith" {
			for process, names := range item.Processes {
				if len(names) != len(value.Modules) {
					return fmt.Errorf("monolith target %q process %q does not contain every module", item.Name, process)
				}
			}
		}
	}
	return nil
}

func packageName(importPath string) string {
	parts := strings.Split(importPath, "/")
	return parts[len(parts)-1]
}
func exported(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' })
	var result string
	for _, part := range parts {
		if part != "" {
			result += strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return result
}

func transportAlias(value string) string { return strings.ToLower(exported(value)) + "Transport" }
