package postgres

import "testing"

func TestRewrite(t *testing.T) {
	tests := []struct {
		name  string
		query string
		want  string
	}{
		{name: "parameters", query: `SELECT ? AS value, '?' AS literal, "?" AS identifier`, want: `SELECT $1 AS value, '?' AS literal, "?" AS identifier`},
		{name: "escaped literal", query: `SELECT 'it''s ?' AS literal, ? AS value`, want: `SELECT 'it''s ?' AS literal, $1 AS value`},
		{name: "transaction text literal", query: `SELECT 'BEGIN IMMEDIATE ?' AS literal`, want: `SELECT 'BEGIN IMMEDIATE ?' AS literal`},
		// INSERT OR IGNORE is left alone: the rewrite used to narrow which
		// constraint violations were suppressed, so the same data migrated on SQLite
		// and aborted here. The shared schema writes explicit ON CONFLICT targets.
		{name: "ignore is not rewritten", query: `INSERT OR IGNORE INTO users(id) VALUES (?)`, want: `INSERT OR IGNORE INTO users(id) VALUES ($1)`},
		{name: "transaction", query: `BEGIN IMMEDIATE`, want: `BEGIN`},
		{name: "identity", query: `CREATE TABLE outbox (sequence INTEGER PRIMARY KEY AUTOINCREMENT)`, want: `CREATE TABLE outbox (sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`},
		{name: "wide integers", query: `CREATE TABLE events (created_at INTEGER NOT NULL, label TEXT NOT NULL, "INTEGER" TEXT)`, want: `CREATE TABLE events (created_at BIGINT NOT NULL, label TEXT COLLATE "C" NOT NULL, "INTEGER" TEXT COLLATE "C")`},
		// Every ordering guarantee the shared repository states is a BYTE
		// property, and PostgreSQL compares TEXT in the database's default
		// collation. Before this rewrite the keyset cursors, the lease fences and
		// the timestamp encoding meant one thing on SQLite and another here.
		{name: "text columns are pinned to the C collation", query: `CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, text TEXT NOT NULL, created_at TEXT NOT NULL)`, want: `CREATE TABLE IF NOT EXISTS messages (id TEXT COLLATE "C" PRIMARY KEY, text TEXT COLLATE "C" NOT NULL, created_at TEXT COLLATE "C" NOT NULL)`},
		{name: "added columns are pinned too", query: `ALTER TABLE messages ADD COLUMN unfurls TEXT NOT NULL DEFAULT '{}'`, want: `ALTER TABLE messages ADD COLUMN unfurls TEXT COLLATE "C" NOT NULL DEFAULT '{}'`},
		// A query is not a table definition, and "text" there is a column.
		{name: "reads are left alone", query: `SELECT id, text FROM messages WHERE created_at > ?`, want: `SELECT id, text FROM messages WHERE created_at > $1`},
		// PRAGMA integrity_check is left alone: rewriting it to SELECT 'ok' produced a
		// check that could never fail. sqlstore reports ErrIntegrityCheckUnsupported
		// for this profile instead.
		{name: "integrity check is not faked", query: `PRAGMA integrity_check`, want: `PRAGMA integrity_check`},
		{name: "table info", query: `PRAGMA table_info(users)`, want: "SELECT ordinal_position - 1, column_name, data_type, CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END, column_default, 0 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'users' ORDER BY ordinal_position"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := rewrite(test.query); got != test.want {
				t.Fatalf("rewrite(%q) = %q, want %q", test.query, got, test.want)
			}
		})
	}
}

func TestRewriteIsIdempotent(t *testing.T) {
	queries := []string{
		"",
		"SELECT ?",
		"SELECT 'BEGIN IMMEDIATE ?'",
		"BEGIN IMMEDIATE",
		"CREATE TABLE items (id INTEGER PRIMARY KEY AUTOINCREMENT)",
		"CREATE TABLE items (id TEXT PRIMARY KEY, label TEXT NOT NULL)",
		"ALTER TABLE items ADD COLUMN note TEXT NOT NULL DEFAULT ''",
	}
	for _, query := range queries {
		if got := rewrite(rewrite(query)); got != rewrite(query) {
			t.Fatalf("rewrite is not idempotent for %q: %q", query, got)
		}
	}
}
