package postgres

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"regexp"
	"strings"
	"sync"

	"github.com/jackc/pgx/v5/stdlib"
	"github.com/sameoldchat/sameoldchat/internal/store/sqlstore"
)

const driverName = "sameoldchat-postgres"

var registerDriver sync.Once

// Open opens PostgreSQL through pgx's database/sql compatibility layer and
// applies the small SQL dialect translation required by the shared repository.
func Open(ctx context.Context, dsn string) (*sqlstore.Store, error) {
	if strings.TrimSpace(dsn) == "" {
		return nil, fmt.Errorf("PostgreSQL storage requires a DSN")
	}
	registerDriver.Do(func() {
		sql.Register(driverName, &queryDriver{delegate: stdlib.GetDefaultDriver()})
	})
	db, err := sql.Open(driverName, dsn)
	if err != nil {
		return nil, fmt.Errorf("open PostgreSQL: %w", err)
	}
	store, err := sqlstore.FromPostgresDB(ctx, db)
	if err != nil {
		_ = db.Close()
		return nil, err
	}
	return store, nil
}

type queryDriver struct{ delegate driver.Driver }

func (d *queryDriver) Open(name string) (driver.Conn, error) {
	connection, err := d.delegate.Open(name)
	if err != nil {
		return nil, err
	}
	return &queryConn{delegate: connection}, nil
}

type queryConn struct{ delegate driver.Conn }

func (c *queryConn) Prepare(query string) (driver.Stmt, error) {
	statement, err := c.delegate.Prepare(rewrite(query))
	if err != nil {
		return nil, err
	}
	return statement, nil
}

func (c *queryConn) Close() error { return c.delegate.Close() }

func (c *queryConn) Begin() (driver.Tx, error) { return c.delegate.Begin() }

func (c *queryConn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx, error) {
	beginner, ok := c.delegate.(driver.ConnBeginTx)
	if !ok {
		return nil, driver.ErrSkip
	}
	return beginner.BeginTx(ctx, opts)
}

func (c *queryConn) PrepareContext(ctx context.Context, query string) (driver.Stmt, error) {
	preparer, ok := c.delegate.(driver.ConnPrepareContext)
	if !ok {
		return c.Prepare(query)
	}
	return preparer.PrepareContext(ctx, rewrite(query))
}

func (c *queryConn) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	execer, ok := c.delegate.(driver.ExecerContext)
	if !ok {
		return nil, driver.ErrSkip
	}
	return execer.ExecContext(ctx, rewrite(query), args)
}

func (c *queryConn) QueryContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	queryer, ok := c.delegate.(driver.QueryerContext)
	if !ok {
		return nil, driver.ErrSkip
	}
	return queryer.QueryContext(ctx, rewrite(query), args)
}

func (c *queryConn) Ping(ctx context.Context) error {
	pinger, ok := c.delegate.(driver.Pinger)
	if !ok {
		return driver.ErrSkip
	}
	return pinger.Ping(ctx)
}

func (c *queryConn) ResetSession(ctx context.Context) error {
	resetter, ok := c.delegate.(driver.SessionResetter)
	if !ok {
		return nil
	}
	return resetter.ResetSession(ctx)
}

func (c *queryConn) CheckNamedValue(value *driver.NamedValue) error {
	checker, ok := c.delegate.(driver.NamedValueChecker)
	if !ok {
		return nil
	}
	return checker.CheckNamedValue(value)
}

var (
	tableInfoPattern     = regexp.MustCompile(`(?i)^\s*PRAGMA\s+table_info\(([^)]+)\)\s*$`)
	autoincrementPattern = regexp.MustCompile(`(?i)INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT`)
	insertIgnorePattern  = regexp.MustCompile(`(?i)^(\s*)INSERT\s+OR\s+IGNORE\s+`)
)

func rewrite(query string) string {
	trimmed := strings.TrimSpace(query)
	if strings.EqualFold(trimmed, "PRAGMA integrity_check") {
		return `SELECT 'ok'`
	}
	if match := tableInfoPattern.FindStringSubmatch(trimmed); match != nil {
		table := strings.TrimSpace(match[1])
		return fmt.Sprintf("SELECT ordinal_position - 1, column_name, data_type, CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END, column_default, 0 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = '%s' ORDER BY ordinal_position", strings.ReplaceAll(table, "'", "''"))
	}
	query = replaceUnquoted(query, "BEGIN IMMEDIATE", "BEGIN")
	query = autoincrementPattern.ReplaceAllString(query, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	if insertIgnorePattern.MatchString(query) {
		query = insertIgnorePattern.ReplaceAllString(query, "${1}INSERT ")
		trimmed = strings.TrimSpace(query)
		if strings.HasSuffix(trimmed, ";") {
			query = strings.TrimSpace(strings.TrimSuffix(trimmed, ";")) + " ON CONFLICT DO NOTHING;"
		} else {
			query = trimmed + " ON CONFLICT DO NOTHING"
		}
	}
	return positionalParameters(query)
}

func replaceUnquoted(query, needle, replacement string) string {
	if needle == "" {
		return query
	}
	var builder strings.Builder
	quoted := byte(0)
	for index := 0; index < len(query); {
		character := query[index]
		if quoted != 0 {
			builder.WriteByte(character)
			index++
			if character == quoted {
				if index < len(query) && query[index] == quoted {
					builder.WriteByte(query[index])
					index++
				} else {
					quoted = 0
				}
			}
			continue
		}
		switch character {
		case '\'', '"', '`':
			quoted = character
			builder.WriteByte(character)
			index++
		case 0:
			builder.WriteByte(character)
			index++
		default:
			if index+len(needle) <= len(query) && strings.EqualFold(query[index:index+len(needle)], needle) {
				builder.WriteString(replacement)
				index += len(needle)
			} else {
				builder.WriteByte(character)
				index++
			}
		}
	}
	return builder.String()
}

func positionalParameters(query string) string {
	var builder strings.Builder
	parameter := 1
	quoted := rune(0)
	characters := []rune(query)
	for index := 0; index < len(characters); index++ {
		character := characters[index]
		if quoted != 0 {
			builder.WriteRune(character)
			if character == quoted {
				if index+1 < len(characters) && characters[index+1] == quoted {
					builder.WriteRune(characters[index+1])
					index++
				} else {
					quoted = 0
				}
			}
			continue
		}
		switch character {
		case '\'', '"', '`':
			quoted = character
			builder.WriteRune(character)
		case '?':
			builder.WriteString(fmt.Sprintf("$%d", parameter))
			parameter++
		default:
			builder.WriteRune(character)
		}
	}
	return builder.String()
}
