package postgres

import "testing"

func TestRewrite(t *testing.T) {
	tests := []struct {
		name  string
		query string
		want  string
	}{
		{name: "parameters", query: `SELECT ? AS value, '?' AS literal, "?" AS identifier`, want: `SELECT $1 AS value, '?' AS literal, "?" AS identifier`},
		{name: "escaped literal", query: `SELECT 'it''s ?' AS literal, ? AS value`, want: `SELECT 'it''s ?' AS literal, $1 AS value`},
		{name: "transaction text literal", query: `SELECT 'BEGIN IMMEDIATE ?' AS literal`, want: `SELECT 'BEGIN IMMEDIATE ?' AS literal`},
		{name: "ignore", query: `INSERT OR IGNORE INTO users(id) VALUES (?)`, want: `INSERT INTO users(id) VALUES ($1) ON CONFLICT DO NOTHING`},
		{name: "transaction", query: `BEGIN IMMEDIATE`, want: `BEGIN`},
		{name: "identity", query: `CREATE TABLE outbox (sequence INTEGER PRIMARY KEY AUTOINCREMENT)`, want: `CREATE TABLE outbox (sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`},
		{name: "wide integers", query: `CREATE TABLE events (created_at INTEGER NOT NULL, label TEXT NOT NULL, "INTEGER" TEXT)`, want: `CREATE TABLE events (created_at BIGINT NOT NULL, label TEXT NOT NULL, "INTEGER" TEXT)`},
		{name: "integrity", query: `PRAGMA integrity_check`, want: `SELECT 'ok'`},
		{name: "table info", query: `PRAGMA table_info(users)`, want: "SELECT ordinal_position - 1, column_name, data_type, CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END, column_default, 0 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'users' ORDER BY ordinal_position"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := rewrite(test.query); got != test.want {
				t.Fatalf("rewrite(%q) = %q, want %q", test.query, got, test.want)
			}
		})
	}
}

func TestRewriteIsIdempotent(t *testing.T) {
	queries := []string{
		"",
		"SELECT ?",
		"SELECT 'BEGIN IMMEDIATE ?'",
		"BEGIN IMMEDIATE",
		"INSERT OR IGNORE INTO users(id) VALUES (?)",
		"CREATE TABLE items (id INTEGER PRIMARY KEY AUTOINCREMENT)",
	}
	for _, query := range queries {
		if got := rewrite(rewrite(query)); got != rewrite(query) {
			t.Fatalf("rewrite is not idempotent for %q: %q", query, got)
		}
	}
}
