package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"testing"
	"time"
)

type authority struct {
	certificate *x509.Certificate
	key         *ecdsa.PrivateKey
}

func newAuthority(t *testing.T, name string) authority {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber:          big.NewInt(1),
		Subject:               pkix.Name{CommonName: name},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(time.Hour),
		IsCA:                  true,
		KeyUsage:              x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
	}
	encoded, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	parsed, err := x509.ParseCertificate(encoded)
	if err != nil {
		t.Fatal(err)
	}
	return authority{certificate: parsed, key: key}
}

// issueServer mints the certificate chatd presents. It carries client
// authentication alongside server authentication, which is what a certificate
// generated by an operator following a single-CA example looks like — and is
// exactly the certificate that must not be accepted as a client.
func (a authority) issueServer(t *testing.T, name string) tls.Certificate {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber: big.NewInt(2),
		Subject:      pkix.Name{CommonName: name},
		DNSNames:     []string{name},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
	}
	encoded, err := x509.CreateCertificate(rand.Reader, template, a.certificate, &key.PublicKey, a.key)
	if err != nil {
		t.Fatal(err)
	}
	leaf, err := x509.ParseCertificate(encoded)
	if err != nil {
		t.Fatal(err)
	}
	return tls.Certificate{Certificate: [][]byte{encoded}, PrivateKey: key, Leaf: leaf}
}

func (a authority) pool() *x509.CertPool {
	pool := x509.NewCertPool()
	pool.AddCert(a.certificate)
	return pool
}

// TestOneAuthorityForBothRolesIsRefused covers the internal-boundary defect
// docs/modules.md documented for a release: `-tls-client-ca ca.crt` on chatd and
// `-chat-ca ca.crt` on the HTTP process named one authority for two independent
// questions — who may connect to chatd, and which server chatd is. Under one
// authority every certificate it issues authenticates as a client to the whole
// internal data plane, including chatd's own server certificate, so anything
// holding the server key is a privileged client of the service it serves.
//
// Documentation cannot be the only thing enforcing that, which is why the
// binary refuses it. Before this check, the shared-CA configuration below
// started normally and served the whole data plane.
func TestOneAuthorityForBothRolesIsRefused(t *testing.T) {
	shared := newAuthority(t, "shared")
	server := shared.issueServer(t, "chatd.internal")
	if err := refuseSelfIssuedClientAuthority(server, shared.pool()); err == nil {
		t.Fatal("a client CA that also issued this server's certificate was accepted")
	}

	// Two authorities: the client CA cannot verify the server leaf, so a
	// correct deployment is untouched.
	clients := newAuthority(t, "clients")
	if err := refuseSelfIssuedClientAuthority(server, clients.pool()); err != nil {
		t.Fatalf("separate authorities were refused: %v", err)
	}

	// A certificate with no leaf at all is a configuration this cannot inspect
	// and must not silently pass.
	if err := refuseSelfIssuedClientAuthority(tls.Certificate{}, clients.pool()); err == nil {
		t.Fatal("an empty server certificate was accepted")
	}
}
